apiVersion: apps/v1
kind: Service
metadata:
  name: portfolio-service
  spec:
    selector:
      io.reality.microservice: portfolio
    ports:
      - name: http
        protocol: TCP
        port: 80
        targetPort: 80
      - name: https
        protocol: TCP
        port: 443
        targetPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-deployment
  labels:
    io.reality.microservice: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      io.reality.microservice: portfolio
  # Pod Template
  template: 
    metadata:
      labels:
        io.reality.microservice: portfolio
    spec:
      containers:
      - name: portfolio-service
        image: localhost:5000/reality.services.portfolio:latest
        ports:
        - containerPort: 80
        env:
          - name: DatabaseName
            value: Portfolio
        envFrom:
          - secretRef:
            name: reality-secrets