apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
spec:
  selector:
    io.foundation.microservice: portfolio
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-service-deployment
  labels:
    io.foundation.microservice: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      io.foundation.microservice: portfolio
  # Pod Template
  template:
    metadata:
      labels:
        io.foundation.microservice: portfolio
    spec:
      containers:
        # Using local registry.
        - name: portfolio-service-pod
          image: unreaalism/foundation.services.portfolio:latest
          ports:
            - containerPort: 80
          env:
            - name: DatabaseName
              value: Portfolio
          envFrom:
            - secretRef:
                name: foundation-secrets
      imagePullSecrets:
        - name: foundation-registry
