apiVersion: v1
kind: Service
metadata:
  name: upx-service
spec:
  selector:
    microservices.reality.io/name: upx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: upx-service-deployment
  labels:
    io.reality.microservice: upx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.reality.microservice: upx
  # Pod Template
  template: 
    metadata:
      labels:
        io.reality.microservice: upx
    spec:
      containers:
      - name: upx-service-pod
        image: localhost:5000/reality.services.upx:latest
        ports:
        - containerPort: 80
        env:
          - name: DatabaseName
            value: UPx
        envFrom:
          - secretRef:
              name: reality-secrets