apiVersion: v1
kind: Service
metadata:
  name: proxy-service
spec:
  type: NodePort
  selector:
    io.reality.microservice: proxy
  ports:
    - name: http
      protocol: TCP
      nodePort: 30000
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      nodePort: 30001
      port: 443
      targetPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-service-deployment
  labels:
    io.reality.microservice: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.reality.microservice: proxy
  # Pod Template
  template: 
    metadata:
      labels:
        io.reality.microservice: proxy
    spec:
      # Using local registry.
      containers:
      - name: proxy-service-pod
        image: unreaalismlity.proxy:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        envFrom:
          - secretRef:
              name: reality-secrets
      imagePullSecrets:
        - name: reality-registry