apiVersion: v1
kind: Service
metadata:
  name: gateway.micro.service
  spec:
    selector:
      io.reality.microservice: gateway
    ports:
      - name: http
        protocol: TCP
        port: 80
        targetPort: 80
      - name: https
        protocol: TCP
        port: 443
        targetPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway.micro.deployment
  labels:
    io.reality.microservice: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.reality.microservice: gateway
  # Pod Template
  template: 
    metadata:
      labels:
        io.reality.microservice: gateway
    spec:
      containers:
      - name: gateway.micro.pod
        image: localhost:5000/reality.services.gateway:latest
        ports:
        - containerPort: 80
        envFrom:
          - secretRef:
              name: reality-secrets