apiVersion: v1
kind: Service
metadata:
  name: identity.micro.service
spec:
  selector:
    io.reality.microservice: identity
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity.micro.deployment
  labels:
    io.reality.microservice: identity
spec:
  replicas: 1
  selector:
    matchLabels:
      io.reality.microservice: identity
  # Pod Template
  template: 
    metadata:
      labels:
        io.reality.microservice: identity
    spec:
      containers:
      - name: identity.micro.pod
        image: localhost:5000/reality.services.identity:latest
        ports:
        - containerPort: 80
        env:
          - name: DatabaseName
            value: Identity
        envFrom:
          - secretRef:
              name: reality-secrets